### ISSUE TITLE
React-Bootstrap dependencies in core

### ISSUE THREAD

**Issue by MHerszak** [SachaG/Zensroom#9]
Hi Sacha,

I just started a fresh project using Vulcan. I did not install `react-bootstrap` because I would like to use `reactstrap` instead. I started the project as you started it in a separate folder and connected to Vulcan packages using `METEOR_PACKAGE_DIRS `. It throws `Error: Cannot find module 'react-bootstrap/lib/Modal` but I don't want to change anything in Vulcan unless it is valuable to the core. This will probably happen for all modules which use react-bootstrap. One solution would be to have another separate core package for use case specific libraries such as reactstrap. Would this be the only way? Just replacing the component doesn't work either since it is going to be called with core. Any ideas? My attempt would be to extract all dependencies from core and build my own component package. Would that make sense?

Regards,

**Comment by SachaG** [comment]
I think for now having the extra dependency on `react-bootstrap` is not a huge deal, I don't think it adds that much weight. 

In the future, we'll use a separate modal implementation (the modal window is the only thing we really depend on) so that we're able to get rid of the dependency in core. 

Another solution would be to split out `vulcan:core-components` from `vulcan:core`, but that might break existing apps so I'd rather just remove the dependency.

**Comment by MHerszak** [comment]
What I am doing is to build backwards from an existing app which uses react-bootstrap and add those into a react-bootstrap package, while I am adding another package for reactstrap. For instance, the modal in reactstrap is a bit different from react-bootstrap. Those packages can be added or removed.

**Comment by MHerszak** [comment]
This wasn't really an issue so it can be closed.
